### ISSUE TITLE
Missing dependencies for tailwind-config

### ISSUE THREAD

**Issue by vsandvold** [fabric-ds/css#46]
I was installing `@fabric-ds/tailwind-config` from npm, and noticed that I have to explicitly install `tailwindcss` and `@tailwindcss/aspect-ratio` as well. It would be helpful if these packages were included in the [package.json](https://github.com/fabric-ds/css/blob/main/packages/tailwind-config/package.json) `dependencies` or `peerDependencies`.

**Comment by digitalsadhu** [comment]
Turns out that this is also the reason that our tailwind config doesn’t work with tailwind play!

See https://github.com/tailwindlabs/play.tailwindcss.com/issues/23#issuecomment-954761912

**Comment by vsandvold** [comment]
Hi! It looks like you have fixed this now.
